version: '3.9'
services:
  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8011:8080
    volumes:
      - ./app:/app
    depends_on:
      - database
  web:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
  rabbitmq:
    image: rabbitmq:4.0.7
    hostname: rabbitmq
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq_volume:/app/rabbitmq_volume
  database:
    image: postgres:16-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_NAME=postgres_db
  volumes:
    postgres_volume:
    rabbitmq_volume:
