version: '3.9'
services:
  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    #image: mlproject-api:latest
    env_file:
      - ./app/.env
    ports:
      - 8011:8080
    volumes:
      - ./app:/app
  # web:
  #   build: ./nginx
  #   ports:
  #     - 80:80 - 443:443
  #   depends_on:
  #     - ./app
  rabbitmq:
    image: rabbitmq:4.0.7
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
  database:
    image: postgres:16-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    expose:
      - 5430:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CartMan1
      - POSTGRES_DB=postgres_db
