version: '3'
services:
  app:
    build: ./app/
    image: mlproject-api:latest
    env_file:
    - ./app/.env 
    ports:
      - 8011:8080
  #   volumes:
  #     -./app:/app
  # web:
  #   build: ./nginx
  #   ports:
  #     -80:80
  #     -443:443
  #     depends_on:
  #       -app  